### PR TITLE
Fahim team

### PR DESCRIPTION
**Pull request by Fahim2965**
I added my pic to the team page.

### CODE REVIEW

**Review by AdrianC167 — CHANGES_REQUESTED** [review]
make it 1200 by 1200 or 1500 by 1500px

**Comment by Fahim2965** [comment]
I did it

**Review by AdrianC167 — APPROVED** [review]
all good

**Review by AdrianC167 — APPROVED** [review]
good

**Review by justinforlenza — APPROVED** [review]

**Pull request merged**
